### ISSUE TITLE
Switching off results in error

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/blocknewsletter#9] opened 2023-03-04 19:54 UTC
Having quite a lot of spam addresses in my newsletter subscription list I wanted to delete them. But there is no option for deleting. So I settled for the next best thing: clicking the checkmark in order to disable them.

But when I did that I received a 500 error. When I checked the log file I found the following error:

> *ERROR* 	2023/03/04 - 20:48:15: ThirtyBeesException: Property Customer->lastname is not valid at line 1092 in file classes/ObjectModel.php

**Comment by musicpanda** [comment] 2023-03-04 19:56
The lastname field was not empty but filled with "www.cutt.us/XZuSl".

**Comment by getdatakick** [comment] 2023-03-06 10:28
Can you provide stacktrace?

**Comment by getdatakick** [comment] 2023-03-06 10:46
This is not a bug in this module. The problem is that there exists customer record (it could be guest account, I'm not sure) with invalid value for 'lastname'.

This module only loads the customer record, changes the registration flag, and resave it.

Do you have any idea how these customer records were created? I tried to create such record in front office and from back office, but every time system rejected the create request. I tried also to update existing customer records, but with the same result.

Do you have some third party checkout module, by any chance?

**Comment by getdatakick** [comment] 2023-03-06 10:57
Is it possible that these are old customer records?

Before 2019 it was possible to create customer records with such names. This was fixed in 1.1.0 by commit [c733d5360d5292c12bb6a899748d9094bc608e05](https://github.com/thirtybees/thirtybees/commit/c733d5360d5292c12bb6a899748d9094bc608e05).

So if these customer records were created in thirty bees 1.0.8 or older, they would go through. After update to 1.1.0 or newer, these records would be invalid. Simple load and save (even in back office) would not be allowed.

**Closed by getdatakick** 2023-03-06 10:57 UTC
Labels: bug
